### ISSUE TITLE
Cannot index string with string "permissions"

### ISSUE THREAD

**Issue by oscaroptics** [iam-veeramalla/shell-scripting-projects#24]
when trying to run the list-users.sh file it says "no users with read access found for devops-by-examples/Python".

Listing users with read access to devops-by-examples/Python...
jq: error (at <stdin>:5): Cannot index string with string "permissions"
No users with read access found for devops-by-examples/Python.

the above is the error i am getting while hitting "./list-users.sh devops-by-examples Python" script in my aws machine

**Comment by arashutosh** [comment]
hey abhishek, sorry i bothered you.. actually i figured it out.. i'm not a collaborator on this repo that's why i was unable to list the users on this repository.

**Comment by arashutosh** [comment]
this issue is resolved. so, i am closing this issue
